/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ngr.KiKi.autolatex.views;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import ngr.KiKi.autolatex.data.Answer;

/**
 *
 * @author KiKi
 */
public class AnswerPanel extends javax.swing.JPanel
{

	private final Answer answer;
	private final QuestionPanel parent;

	/**
	 * Creates new form AnswerPanel
	 */
	public AnswerPanel (QuestionPanel p, Answer a)
	{
		initComponents ();

		parent = p;
		answer = a;

		init ();
	}

	private void init ()
	{
		jCheckBoxCorrect.setSelected (answer.isCorrect ());
		jCheckBoxCorrect.addActionListener ((ActionEvent ae) ->
		{
			update ();
		});

		jTextAreaText.setText (answer.toString ());
		jTextAreaText.getDocument ().addDocumentListener (new DocumentListener ()
		{

			@Override
			public void insertUpdate (DocumentEvent de)
			{
				update ();
			}

			@Override
			public void removeUpdate (DocumentEvent de)
			{
				update ();
			}

			@Override
			public void changedUpdate (DocumentEvent de)
			{
				update ();
			}
		});
	}

	public Answer getAnswer ()
	{
		return answer;
	}

	private void update ()
	{
		answer.setCorrect (jCheckBoxCorrect.isSelected ());
		answer.setText (jTextAreaText.getText ());
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jCheckBoxCorrect = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaText = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(350, 40));

        jCheckBoxCorrect.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCheckBoxCorrectActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaText.setColumns(20);
        jTextAreaText.setRows(2);
        jScrollPane1.setViewportView(jTextAreaText);

        jButton1.setText("-");
        jButton1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxCorrect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jCheckBoxCorrect))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxCorrectActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCheckBoxCorrectActionPerformed
    {//GEN-HEADEREND:event_jCheckBoxCorrectActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxCorrectActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
		parent.removeAnswer (this);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxCorrect;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaText;
    // End of variables declaration//GEN-END:variables
}
