/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ngr.KiKi.autolatex.views;

import java.awt.Color;
import java.util.Map;
import javax.swing.border.TitledBorder;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import net.miginfocom.layout.CC;
import net.miginfocom.layout.LC;
import net.miginfocom.swing.MigLayout;
import ngr.KiKi.autolatex.data.Answer;
import ngr.KiKi.autolatex.data.Question;

/**
 *
 * @author KiKi
 */
public class QuestionPanel extends javax.swing.JPanel
{

	private final Question question;
	private final JFrameMain parent;

	/**
	 * Creates new form QuestionPanel
	 */
	public QuestionPanel (JFrameMain p, Question q)
	{
		initComponents ();

		question = q;
		parent = p;

		init ();
	}

	private void init ()
	{
		jTextAreaText.setText (question.toString ());
		jTextAreaText.getDocument ().addDocumentListener (new DocumentListener ()
		{

			@Override
			public void insertUpdate (DocumentEvent de)
			{
				updateValues ();
			}

			@Override
			public void removeUpdate (DocumentEvent de)
			{
				updateValues ();
			}

			@Override
			public void changedUpdate (DocumentEvent de)
			{
				updateValues ();
			}

		});

		initAnswers ();

		initGroups ();

		updateDisplay ();
	}

	private void initGroups ()
	{
		Map<String, Color> groups = parent.getGroups ();
		groups.keySet ().stream ().forEach ((g)->{
			jComboBoxGroup.addItem (g);
		});
		MyColorComboBoxRenderer renderer = new MyColorComboBoxRenderer (jComboBoxGroup);
		renderer.setValues (groups);
		jComboBoxGroup.setRenderer (renderer);
	}

	private void initAnswers ()
	{
		jPanelAnswers.removeAll ();
		jPanelAnswers.setLayout (new MigLayout (new LC ().fillX ().hideMode (3)));

		question.getAnswers ().stream ().forEach ((a) ->
		{
			jPanelAnswers.add (new AnswerPanel (this, a), new CC ().wrap ().growX ());
		});

		jPanelAnswers.add (jButtonAddAnswer);
	}

	public void removeAnswer (AnswerPanel ap)
	{
		question.getAnswers ().remove (ap.getAnswer ());
		initAnswers ();

		updateDisplay ();
	}

	private void updateDisplay ()
	{
		((TitledBorder) jScrollPaneAnswers.getBorder ()).setTitle (question.getAnswers ().size () + " réponses");
		repaint ();
	}

	private void updateValues ()
	{
		question.setGroup ((String) jComboBoxGroup.getSelectedItem ());
		question.setText (jTextAreaText.getText ());
		parent.updateQR ();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaText = new javax.swing.JTextArea();
        jPanelConfig = new javax.swing.JPanel();
        jScrollPaneAnswers = new javax.swing.JScrollPane();
        jPanelAnswers = new javax.swing.JPanel();
        jButtonAddAnswer = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jComboBoxGroup = new javax.swing.JComboBox();

        setMinimumSize(new java.awt.Dimension(389, 168));
        setPreferredSize(new java.awt.Dimension(389, 168));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Intitulé"));

        jTextAreaText.setColumns(20);
        jTextAreaText.setRows(3);
        jScrollPane1.setViewportView(jTextAreaText);

        jPanelConfig.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuration"));

        javax.swing.GroupLayout jPanelConfigLayout = new javax.swing.GroupLayout(jPanelConfig);
        jPanelConfig.setLayout(jPanelConfigLayout);
        jPanelConfigLayout.setHorizontalGroup(
            jPanelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelConfigLayout.setVerticalGroup(
            jPanelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jScrollPaneAnswers.setBorder(javax.swing.BorderFactory.createTitledBorder("Réponses"));

        jButtonAddAnswer.setText("+");
        jButtonAddAnswer.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonAddAnswer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonAddAnswerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAnswersLayout = new javax.swing.GroupLayout(jPanelAnswers);
        jPanelAnswers.setLayout(jPanelAnswersLayout);
        jPanelAnswersLayout.setHorizontalGroup(
            jPanelAnswersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAnswersLayout.createSequentialGroup()
                .addComponent(jButtonAddAnswer)
                .addGap(0, 360, Short.MAX_VALUE))
        );
        jPanelAnswersLayout.setVerticalGroup(
            jPanelAnswersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAnswersLayout.createSequentialGroup()
                .addComponent(jButtonAddAnswer)
                .addGap(0, 152, Short.MAX_VALUE))
        );

        jScrollPaneAnswers.setViewportView(jPanelAnswers);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Catégorie"));

        jComboBoxGroup.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBoxGroupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxGroup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPaneAnswers)
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneAnswers, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelConfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxGroupActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBoxGroupActionPerformed
    {//GEN-HEADEREND:event_jComboBoxGroupActionPerformed
		String selected = (String) jComboBoxGroup.getSelectedItem ();
		if (selected.equals ("Nouvelle catégorie"))
		{

		}
		updateValues ();
    }//GEN-LAST:event_jComboBoxGroupActionPerformed

    private void jButtonAddAnswerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonAddAnswerActionPerformed
    {//GEN-HEADEREND:event_jButtonAddAnswerActionPerformed
		Answer newAnswer = question.addAnswer ("Nouvelle réponse", false);
		jPanelAnswers.remove (jButtonAddAnswer);
		jPanelAnswers.add (new AnswerPanel (this, newAnswer), new CC ().wrap ().growX ());
		jPanelAnswers.add (jButtonAddAnswer);

		updateDisplay ();
    }//GEN-LAST:event_jButtonAddAnswerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddAnswer;
    private javax.swing.JComboBox jComboBoxGroup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAnswers;
    private javax.swing.JPanel jPanelConfig;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneAnswers;
    private javax.swing.JTextArea jTextAreaText;
    // End of variables declaration//GEN-END:variables
}
